MAX_CHARS_ALLOWED_IN_TELEGRAM_MSG = 4096
DIST_ID_CBE = 539
STR_SLOTS_NOT_AVAILABLE = 'OOPS, slots not available currently. Try again after sometime...'
STR_REPLY_TO_GREETINGS = 'hope you are safe and sound!\nTo get started, click /start and follow along.'
STR_REPLY_TO_UNRECOGNIZED_TEXT = "I don't understand what you are talking. If you are stuck, you might want to click on /help"
STR_REPLY_TO_START_COMMAND = 'welcome to this bot. I can help you find vaccination centres and the availability of the slots. To know more, click /help' 
STR_REPLY_TO_HELP_COMMAND = "I can help you find vaccination centres and the availability of the slots for Coimbatore district. We directly fetch all these data real-time.\n\nYou can get the details by sending these commands to me:\n\n/cbe - gets all the vaccination centres in Coimbatore with vaccines available today\n/poy - gets all the vaccination centres in Pollachi that has vaccines available today\n/7dcbe - gets all the vaccination centres for the next 1 week in Coimbatore with vaccines available to book\n/start - to go to the start\n\nIf you are bored, try sending me a 'hi'."
URL_BASE = 'https://cdn-api.co-vin.in/api'
URL_ENDPOINT_FINDBYDISTRICT = '/v2/appointment/sessions/public/findByDistrict'
URL_ENDPOINT_CALENDARBYDISTRICT = '/v2/appointment/sessions/public/calendarByDistrict'